# Generated by Django 3.2.20 on 2023-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='include_jaeger',
            field=models.BooleanField(default=False),
        ),
    ]
